name: lambda_zip_test
on: [push]
jobs:
  lambda_demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build project
        run: |
           ./buildspec.yml
      - name: lambda_code_update
        run: |
          aws lambda update-function-code --function-name Microservices --zip-file fileb://./deployment_zip/lambda_zip.zip
